version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SAMTest"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hu2s1sfq92o8"
s3_prefix = "SAMTest"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
